name: Cryptol Checks

on: [push, pull_request]

jobs:
  ci-load:
    uses: ./.github/workflows/cryptol-remote-api.yml
    with:
      ci_script_name: ci_load.py

  ci-check:
    uses: ./.github/workflows/cryptol-remote-api.yml
    with:
      ci_script_name: ci.py

  ci-prove:
    uses: ./.github/workflows/cryptol-remote-api.yml
    with:
      ci_script_name: ci_prove.py
