name: Cryptol Checks

on: [push, pull_request]

env:
  PYTHON_VERSION: 3.11

jobs:
  ci-load:
    runs-on: ubuntu-latest
    services:
      cryptol-remote-api:
        image: ghcr.io/weaversa/cryptol-course/nightly
        ports:
          - 8080:8080
        options: -v ${{ github.workspace }}:/home/cryptol
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION
      # Install Cryptol Client  
      - run: pip install cryptol
      # Load all files
      - run: python .ci/ci_load.py
        env:
          CRYPTOL_SERVER_URL: http://0.0.0.0:8080

  ci-check:
    needs: ci-load
    runs-on: ubuntu-latest
    services:
      cryptol-remote-api:
        image: ghcr.io/weaversa/cryptol-course/nightly
        ports:
          - 8080:8080
        options: -v ${{ github.workspace }}:/home/cryptol
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION
      # Install Cryptol Client  
      - run: pip install cryptol
      - name: set pythonpath
        run: echo "PYTHONPATH=${PYTHONPATH}:${PWD}/.ci" >> $GITHUB_ENV
      # Run checks
      - run: for f in `find . -name "ci.py"`; do python $f; done
        env:
          CRYPTOL_SERVER_URL: http://0.0.0.0:8080

  ci-prove:
    needs: ci-load
    runs-on: ubuntu-latest
    services:
      cryptol-remote-api:
        image: ghcr.io/weaversa/cryptol-course/nightly
        ports:
          - 8080:8080
        options: -v ${{ github.workspace }}:/home/cryptol
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION
      # Install Cryptol Client  
      - run: pip install cryptol
      - name: set pythonpath
        run: echo "PYTHONPATH=${PYTHONPATH}:${PWD}/.ci" >> $GITHUB_ENV
      # Run checks
      - run: for f in `find . -name "ci_prove.py"`; do python $f; done
        env:
          CRYPTOL_SERVER_URL: http://0.0.0.0:8080
