name: Cryptol Checks

on: [push, pull_request]

jobs:
  ci-load:
    uses: ./.github/workflows/cryptol-remote-api.yml
    with:
      ci_cryptol_script: ci_load.py

  ci-check:
    uses: ./.github/workflows/cryptol-remote-api.yml
    with:
      ci_cryptol_script: ci.py

  ci-prove:
    uses: ./.github/workflows/cryptol-remote-api.yml
    with:
      ci_cryptol_script: ci_prove.py
