name: Saw Checks

on: [push, pull_request]

jobs:
  saw-tutorial:
    uses: ./.github/workflows/saw-remote-api.yml
    with:
      saw_directories: "labs/SAW/rotl labs/SAW/addRow labs/SAW/null labs/SAW/Game/DLC labs/SAW/ceilLog2"

  saw-demos:
    uses: ./.github/workflows/saw-remote-api.yml
    with:
      saw_directories: "labs/Demos/SAW/Salsa20"
    