name: SAW-Remote-API Template

on:
  workflow_call:
    inputs:
      saw_directories:
        required: true
        type: string
env:
  SAW_SERVER_URL: http://0.0.0.0:8080

jobs:
  saw_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/weaversa/cryptol-course:2.13
      options: --user root
    services:
      saw-remote-api:
        image: ghcr.io/galoisinc/saw-remote-api:nightly
        ports:
          - 8080:8080
        options: -v ${{ github.workspace }}:${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Saw Proofs
        run: for word in ${{ inputs.saw_directories }}; do make prove -C $word; done